### ISSUE TITLE
Possibly missing pathway names in some rows from the Jan 2023 release of mouse data

### ISSUE THREAD

**Issue by yyw-informatics** [BaderLab/EnrichmentMap_monthlyGenesetBuild#18]
Hi 
I don't know if this is normal, but I noticed that some rows in the gmt file start with gene symbols without pathway ID and names.

* To download and read the file:
```
gmt_url <-'http://download.baderlab.org/EM_Genesets/current_release/Mouse/symbol/Mouse_GO_AllPathways_no_GO_iea_January_01_2023_symbol.gmt'
gmt <- "Mouse_GO_AllPathways_no_GO_iea_January_01_2023_symbol.gmt"
download.file(url = gmt_url, destfile = gmt)
pathways <- utils::read.delim(gmt, header = F)
```
* Preview correct rows
![image](https://user-images.githubusercontent.com/38868191/211684254-3650a836-cf14-4962-95c6-64bc5582a6cc.png)

* Preview rows without pathway ID or names 
![image](https://user-images.githubusercontent.com/38868191/211684587-00c4664c-94d8-4b7f-9954-16eb41853cf1.png)

* As gene symbols occupied the first column, so the first column is no longer unique, which can cause problems in downstream analysis.
![image](https://user-images.githubusercontent.com/38868191/211684503-41b93431-4f10-40ce-be7d-1f5228940ffc.png)

Thanks,
Yuanyuan

**Comment by risserlin** [comment]
The GMT file is not a matrix/dataframe.  It is a list of lists.  By loading it in using 
pathways <- utils::read.delim(gmt, header = F)
you are loading it in as a data.frame and I think it is messing up the structure of the file.  

I think there might be a few different packages but I use GSA R package to read in the gmt file so that it preserves the list of list structure - https://www.rdocumentation.org/packages/GSA/versions/1.03.2/topics/GSA.read.gmt

When I load in the gmt with the above function I don't have any duplicated geneset names.

**Comment by yyw-informatics** [comment]
Thanks! One of the packages that I use have the code above to read GMT files, I will use the GSA package to read it as you suggested.
